source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftMVVMBinding_Example', :exclusive => true do
  pod "SwiftMVVMBinding", :path => "../"
end

target 'SwiftMVVMBinding_Tests', :exclusive => true do
  pod "SwiftMVVMBinding", :path => "../"
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end


post_install do |installer|
    # Patch ENABLE_TESTABILITY = YES on the SwiftMVVM pod target
    target = installer.pods_project.native_targets.find { |target| target.name == "SwiftMVVMBinding" }
    debug_config = target.build_configurations.find { |config| config.name == "Debug" }
    debug_config.build_settings["ENABLE_TESTABILITY"] = "YES"
end
