source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Bindings_Example', :exclusive => true do
  pod "Bindings", :path => "../"
end

target 'Bindings_Tests', :exclusive => true do
  pod "Bindings", :path => "../"
  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
end
